---
title: "Untitled"
output: html_document
date: "2022-10-31"
---

## Question 1: Wild Life Population Density
```{r}
#a
#Initialising the enviroment
setwd("~/Desktop/Statistical Computing/CW/Statistical-Computing-CW1")
eco.df <- read.table("ecoStudy.txt",header = T)
#Turning habitat variable into factor for later plotting and analysis using it
eco.df$habitat <- factor(eco.df$habitat,levels=c("A","B","C"),labels=c("A","B","C"))
attach(eco.df)

#i
#For these questions I will report my answers to 3 d.p.

round(min(density),3)
#minimum density is 0

#Selecting 1st quantile from the density column of eco-study dataset
round(quantile(density)[[2]],3)
#1st quantile of density is 1.413 to (3 d.p.)

round(median(density),3)
#Median of density is 2.744 (3 d.p.)

#Selecting 3rd quantile
round(quantile(density)[[4]],3)
#3rd quantile of density is 4.193 (3 d.p.)

round(max(density),3)
#maximum value of density is 20.497 (3 d.p.)

#ii
table(habitat)
#For habitat A, B and C there are 100, 125 and 75 observations in each respectively
```

```{r}
#b
#Creating new column in eco-study dataframe
eco.df$logDensity <- log(density + 1)

#Saving plot created below to pdf file called Boxplot.pdf
pdf(file="Boxplot.pdf")

#Creating graphic of side by side box plots
par(mfrow=c(2,1))

boxplot(density~habitat,
        main="Boxplot of density in each habitat",
        xlab="Habitat type",
        ylab="Density",
        col=c("red","blue","green"))

boxplot(logDensity~habitat,
        main="Boxplot of log density in each habitat",
        xlab="Habitat type",
        ylab="Log density",
        col=c("red","blue","green"))

dev.off()

#NEED TO SORT OUT SAVING THIS PROPERLY
```
```{r}
#Creating vectors to store the observed densities of each habitat type
density.A <- density[habitat=="A"]
density.B <- density[habitat=="B"]
density.C <- density[habitat=="C"]

#calculating the denominator of F statistic
F.stat.denom <- (sum((density.A-mean(density.A))^2)+
  sum((density.B-mean(density.B))^2)+
  sum((density.C-mean(density.C))^2))/(300-3)

#calculating the numerator of F statistic
F.stat.numerator <- ((100*((mean(density.A)-mean(density))^2))+
  (125*((mean(density.B)-mean(density))^2))+
  (75*((mean(density.C)-mean(density))^2)))/2

#Calculating F statistic
F.stat <- F.stat.numerator/F.stat.denom

#Finding p-value, as pf is probability that x from a RV X~F_{2}{297} is less than F.stat value the probability to be equal or larger is 1-pf
1-pf(F.stat,2,297)


#Using tapply to find the F-stat instead

#First, creating a function to calculate the numerator and denominator values for each habitat type
F.stat <- function(vec=NULL){
  
  numerator<-(length(vec)*(mean(vec)-mean(density))^2)/2
  denominator<-(sum((vec-mean(vec))^2))/(300-3)
  
  #Storing in a list so can extract both values from the function output
  output <- list("num"=numerator,"den"=denominator)
  
  return(list("num"=numerator,"den"=denominator))
}

#Applying the function to each habitat type separately using the tapply function
tapply.out.Fstat<-tapply(density,habitat,FUN=F.stat)

#Calculating the F statistic by extracting and summing the numerator and denominator parts of the tapply output
tapply.F.stat<-sum(c(tapply.out.Fstat$A$num,tapply.out.Fstat$B$num,tapply.out.Fstat$C$num))/
  sum(c(tapply.out.Fstat$A$den,tapply.out.Fstat$B$den,tapply.out.Fstat$C$den))
```

```{r}
#function to calculate the residuals in the ith habitat
residual.func<- function(x){

  residuals <- x-mean(x)
  
  return(residuals)
}

#Calculating residuals for each habitat using tapply
residuals.list <- tapply(density, habitat, residual.func)
#Extracting residuals values from list and putting into a vector
residuals<-c(residuals.list$A,residuals.list$B,residuals.list$C)

#Creating QQ plot
sorted.residuals<-sort(residuals)
sorted.normal.dist<-sort(rnorm(300))

plot(x=sorted.normal.dist,y=sorted.residuals,
     xlab="Theoretical quantiles",
     ylab="Sample quantiles",
     main="QQ plot of residuals")
#Adding in reference line
qqline(residuals, col = "red", lwd = 2)

#Looking at the QQ plot the tails diverge dramatically from the reference line giving evidence that the residuals are not normally distributed.
```

## Question 2: Mixture Models
```{r}
calcLogMix2Gamma <- function(x,alpha,beta,p){
  
  #input argument checking
  if(is.numeric(x)==F){
    stop("x is not a numeric vector")
  }else if(length(alpha)!=2 | is.numeric(alpha)==F){
    stop("alpha needs to a numeric vector of length 2")
  }else if(length(beta)!=2 | is.numeric(beta)==F){
    stop("beta needs to a numeric vector of length 2")
  }else if(is.numeric(p)==F | p>1 | p<0 | length(p)!=1){
    stop("p must be a single numeric value between 0 and 1 inclusive")
  }
  
  #calculating the pdf for each value of x using the provided formula
  prob.dist<-p*(x^(alpha[1]-1)*exp(-beta[1]*x)*beta[1]^alpha[1])/gamma(alpha[1])+(1-p)*(x^(alpha[2]-1)*exp(-beta[2]*x)*beta[2]^alpha[2])/gamma(alpha[2])
  
  #calculating the log of the joint probability distribution
  log.prob.dist <- log(prod(prob.dist))
  
  return(log.prob.dist)
}


#Creating objects for the function
x <- c(0.06, 2.32, 4.81, 0.02, 2.33, 2.18, 0.83, 2.45, 2.10, 3.27)
alpha <- c(0.5, 6)
beta <- c(0.5, 2.5)
p <- 0.35

#Using calcLogMixGamma function with required inputs and rounding to 3 d.p.
round(calcLogMix2Gamma(x,alpha,beta,p),3)

#The answer of the log joint pdf is -13.928 (to 3 d.p.)
```

```{r}
#Testing making a function to find density of normal gamma variable to see if the structure of my function matches

calcGamma <- function(x,alpha,beta){
  num <- (beta^alpha)*(x^(alpha-1))*exp(-beta*x)
  denom <- gamma(alpha)
  output <- num/denom
  return(output)
}

calcGamma(3,2,5)

dgamma(c(2,3,4),2,5)
#Note that density returns a vector of values if x is a vector (because not joint pdf)
```



## Question 3: Reimann Integration

```{r}
smoothCurve <- function(x,alpha,beta,p,q,k){
  #To calculate g(x) I split up the term to allow easier manual checking of values and reduce errors due to missing a bracket
  
  #calculating numerator and denominator in log term of g(x) function
  numerator <- (gamma(x+beta)^k)*(p^alpha)*(q^beta)
  denominator <- (gamma(alpha)^k)*(gamma(beta)^k)
  
  #combining parts of g(x) to calculate g(x) value
  g <- sin((1/(2*alpha))*log(numerator/denominator))

  return(g)
}

calcMidRiemannLoop <- function(xVec,alpha,beta,p,q,k){
  #setting up vector to store areas of each (x_{i-1},x_{i}) segment
  interval.area<-rep(0,length(xVec)-1)
  
  #loop to calculate the area in each interval
  #As we are told that the x intercept is not crossed in any interval we do not need to worry about 
  #having to split the area into 2 and calculating the area seperately for part above and below x-axis
  
  for (i in 2:length(xVec)){
    #Caclulating x input for g(x) function
    x <- (xVec[i]+xVec[i-1])/2
    
    #using equation 6 with absolute value as area cannot be negative
    interval.area[i-1] <- abs((xVec[i]-xVec[i-1])*smoothCurve(x,alpha,beta,p,q,k))
  }
  
  #Calculating total area
  approx.area <- sum(interval.area)
  
  return(approx.area)
}

calcMidRiemann <- function(xVec,alpha,beta,p,q,k){
  #Checking xVec argument
  if (is.numeric(xVec)==F){
    
    stop("xVec argument must be numeric")
    
  }else if (length(xVec)==1){
    
    stop("xvec argument must be a vector of 2 or more values")
  }else if (length(alpha)>1 | is.numeric(alpha)==F | alpha<=0){
    stop("alpha must be a single positive numeric value")
  }else if (length(beta)>1 | is.numeric(beta)==F | beta<=0){
    stop("beta must be a single positive numeric value")
  }else if (length(p)>1 | is.numeric(p)==F){
    stop("p must be a single numeric value")
  }else if (length(k)>1 | is.numeric(k)==F){
    stop("k must be a single numeric value")
  }else if (length(q)>1 | is.numeric(q)==F){
    stop("q must be a single numeric value")
  }
  #checking to see if all values in xVec are larger than the last (strictly increasing)
  ifelse(xVec != sort(xVec),stop("xVec argment must be a strictly increasing vector of values"),NA)

  #vector containing the intervals to calculate the area of
  interval.region<-xVec[-1]-xVec[1:length(xVec)-1]
  
  #values of x to input into g(x) for each of the corresponding intervals
  g.func.input <-(xVec[-1]+xVec[1:length(xVec)-1])/2
  
  #calculating each intervals approximate area using equation (6) without summation
  interval.area <- abs(interval.region*smoothCurve(g.func.input,alpha,beta,p,q,k))
  #summing individual areas to find total area 
  approx.area <- sum(interval.area)
  
  return(approx.area)
}

#Creating vector of intervals as specified
xVec <- seq(from=2,to=8,by=0.01)

round(calcMidRiemann(xVec,2.1,0.5,3,6,2),3)
#The answer for (e) is 4.316 to 3 d.p.

#checking against loop version
calcMidRiemannLoop(xVec,2.1,0.5,3,6,2)


plot(xVec,smoothCurve(xVec,2.1,0.5,3,6,2))

#Finish checking the other argments!

# #Testing
# library(DescTools)
# AUC(xVec,smoothCurve(xVec,2.1,0.5,3,6,2),absolutearea=TRUE)
# 
# xVec <- c(2,4,5,-2,1,7)
# ifelse(xVec != sort(xVec),stop("xVec argment must be a strictly increasing vector of values"),NA)
```


```{r}

calcMidRiemannAreas <- function(xSeqList,alpha,beta,p,q,k){
  #Using sapply to apply calcMidRiemann function to each list element and return each calculated area as an element of a vector
  vector.of.areas <- sapply(xSeqList,calcMidRiemann,alpha=alpha,beta=beta,p=p,q=q,k=k)
  
  #Summing areas calculated for each list element to find total area
  total.area<-sum(vector.of.areas)
  
  return(sum(list.of.areas))
}

#creating list of sequences as defined in (g)
xSeqList <- list(seq(from=3.5,to=8,by=0.01),seq(from=2,to=4.3,by=0.1),seq(from=1.07,to=9.012,by=0.001))

round(calcMidRiemannAreas(xSeqList,1.9,0.75,2.15,7,1.65),3)
#Total area is 10.847 to 3 d.p.

#checking answer using calcMidRiemann multiple times
calcMidRiemann(seq(from=3.5,to=8,by=0.01),1.9,0.75,2.15,7,1.65)+
  calcMidRiemann(seq(from=2,to=4.3,by=0.1),1.9,0.75,2.15,7,1.65)+
  calcMidRiemann(seq(from=1.07,to=9.012,by=0.001),1.9,0.75,2.15,7,1.65)
```

```{r}

weatherSeqProb <- function(weatherSeq,trProbs,initProbs){
  
  #Finding the length weather sequence
  weather.seq.length <- length(weatherSeq)
  
  #Finding initial probability of chosen sequence
  if (weatherSeq[1]=="s"){
    initial.prob <- initProbs[1]
  }else if (weatherSeq[1]=="c"){
    initial.prob <- initProbs[2]
  }else if (weatherSeq[1]=="r"){
    initial.prob <- initProbs[3]
  }
  #Assigning numeric values to weather sequence letters to be able to call indexes of matrix
  weatherSeq.numeric <- ifelse(weatherSeq=="s",1,ifelse(weatherSeq=="c",2,3))
  
  #Setting up vector to store each transition probability in
  transition.prob<-rep(0,length(weatherSeq))
  
for (i in 2:length(weatherSeq)){
  #trProbs[i,j] is the probability to go from state i to state j thus i si the last weather state and j is current which has been stored in weatherSeq.numeric
  transition.prob[i] <- trProbs[weatherSeq.numeric[i-1],weatherSeq.numeric[i]]
}
  
  #Putting initial weather probability into vector
  transition.prob[1] <- initial.prob
  
  #Calculating log total probability
  total.prob.log <- log(prod(transition.prob))
  
  return(total.prob.log)
}

weatherSeq <- c("c","s","c","r","s","s")
trProbs <- matrix(c(0.5,0.4,0.1,0.33,0.35,0.32,0.3,0.3,0.4),nrow=3,ncol=3,byrow = T)
initProbs <- c(0.45,0.25,0.3)

round(weatherSeqProb(weatherSeq,trProbs,initProbs),3)
#log probability of weather sequence is -6.448 (3 d.p.)



# #Testing to see code working properly
# weatherSeq.numeric <- ifelse(weatherSeq=="s",1,ifelse(weatherSeq=="c",2,3))
#   
# transtion.prob<-rep(0,length(weatherSeq))
# for (i in 2:length(weatherSeq)){
#   transtion.prob[i] <- trProbs[weatherSeq.numeric[i-1],weatherSeq.numeric[i]]
# }  
# 
# trProbs
```

```{r}

weatherColourProbs <- function(colourSeq,emitProbs,weatherSeq,trProbs,initProbs){
  
  #calculate probabilities for weather as before
  total.weather.prob <- exp(weatherSeqProb(weatherSeq,trProbs,initProbs))
  
  weatherSeq.numeric <- ifelse(weatherSeq=="s",1,ifelse(weatherSeq=="c",2,3))
  colourSeq.numeric <- ifelse(colourSeq=="B",1,2)
  
  colour.trans.prob <- rep(0,length(colourSeq))
  for (i in 1:length(colourSeq)){
    #Storing prob of selecting the jacket in the ith position sequence for the ith weather condition chosen 
  colour.trans.prob[i] <- emitProbs[weatherSeq.numeric[i],colourSeq.numeric[i]]  
  }
  
  total.prob <- total.weather.prob*prod(colour.trans.prob)
  log.total.prob <- log(total.prob)
  return(log.total.prob)
}


#Setting up objects to input into function
weatherSeq <- c("r","s","c","r","c","r","s","s")
colourSeq <- c("B","W","W","B","B","W","W","W")
initProbs <- c(0.35,0.45,0.2)
trProbs <- matrix(c(0.55,0.25,0.2,0.25,0.35,0.4,0.2,0.15,0.65),nrow=3,ncol=3,byrow = T)
emitProbs <- matrix(c(0.2,0.8,0.55,0.45,0.9,0.1),nrow=3,ncol=2,byrow = T)

round(weatherColourProbs(colourSeq,emitProbs,weatherSeq,trProbs,initProbs),3)
#Answer is -15.121 (3 d.p.)

#Need to make comments and clean up code (indentation)
#Check that have not repeated code in last function???
#Change if else to have vector of 1 longer length with new 1st element equal to old 1st element (then for loop would do all of the work)

#Need to put into normal R script
```



